language: csharp
mono: none
dotnet: 1.0.4
dist: trusty

install:
    - dotnet restore ValiDoc.sln

script:
    - dotnet build ValiDoc.sln
    - dotnet test ./test/ValiDoc.Integration.Tests/ValiDoc.Integration.Tests.csproj
    - dotnet test ./test/ValiDoc.Unit.Tests/ValiDoc.Unit.Tests.csproj
